version: '3.8'

x-mongo: &mongo
  image: mongo:4.2.8
  entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  networks:
    - cqrs

services:
  user_mongo0:
    <<: *mongo
    hostname: user_mongo0
    container_name: cqrs_user_mongo0
    ports:
      - 27017:27017
  user_mongo1:
    <<: *mongo
    hostname: user_mongo1
    container_name: cqrs_user_mongo1
    ports:
      - 27018:27017
  user_mongo2:
    <<: *mongo
    hostname: user_mongo2
    container_name: cqrs_user_mongo2
    ports:
      - 27019:27017
  billing_mongo0:
    <<: *mongo
    hostname: billing_mongo0
    container_name: cqrs_billing_mongo3
    ports:
      - 27020:27017
  billing_mongo1:
    <<: *mongo
    hostname: billing_mongo1
    container_name: cqrs_billing_mongo4
    ports:
      - 27021:27017
  billing_mongo2:
    <<: *mongo
    hostname: billing_mongo2
    container_name: cqrs_billing_mongo5
    ports:
      - 27022:27017
  zookeeper:
    container_name: cqrs_zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cqrs
  kafka:
    container_name: cqrs_kafka
    hostname: kafka
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - cqrs

networks:
  cqrs:
    driver: bridge
